all: svg convert

svg: plain rhine boon

convert: 
	for i in svg/*.svg; do inkscape --export-area-page --export-png=maps/`basename -s .svg $$i`.png $$i; done

plain:
	./json2image.py svg/16.svg data/16.json
	./json2image.py svg/18.svg data/18.json
	./json2image.py svg/61.svg data/61.json
	./json2image.py svg/62.svg data/62.json
	./json2image.py svg/63.svg data/63.json
	./json2image.py svg/65.svg data/65.json
	./json2image.py svg/66.svg data/66.json
	./json2image.py svg/67.svg data/67.json
	./json2image.py svg/68.svg data/68.json
	./json2image.py svg/SB55.svg data/SB55.json
	./json2image.py svg/SB60.svg data/SB60.json
	./json2image.py svg/SB69.svg data/SB69.json
	./json2image.py svg/516.svg data/516.json
	./json2image.py svg/529.svg data/529.json
	./json2image.py svg/537.svg data/537.json
	./json2image.py svg/541.svg data/541.json
	./json2image.py svg/550.svg data/550.json
	./json2image.py svg/551.svg data/551.json
	./json2image.py svg/600.svg data/600.json
	./json2image.py svg/601.svg data/601.json
	./json2image.py svg/602.svg data/602.json
	./json2image.py svg/603.svg data/603.json
	./json2image.py svg/604.svg data/604.json
	./json2image.py svg/605.svg data/605.json
	./json2image.py svg/606.svg data/606.json
	./json2image.py svg/607.svg data/607.json
	./json2image.py svg/608.svg data/608.json
	./json2image.py svg/609.svg data/609.json
	./json2image.py svg/610.svg data/610.json
	./json2image.py svg/611.svg data/611.json
	./json2image.py svg/612.svg data/612.json
	./json2image.py svg/613.svg data/613.json
	./json2image.py svg/614.svg data/614.json
	./json2image.py svg/615.svg data/615.json
	./json2image.py svg/630.svg data/630.json
	./json2image.py svg/631.svg data/631.json
	./json2image.py svg/632.svg data/632.json
	./json2image.py svg/633.svg data/633.json
	./json2image.py svg/635.svg data/635.json
	./json2image.py svg/636.svg data/636.json
	./json2image.py svg/637.svg data/637.json
	./json2image.py svg/638.svg data/638.json
	./json2image.py svg/640.svg data/640.json
	./json2image.py svg/680.svg data/680.json
	./json2image.py svg/800.svg data/800.json
	./json2image.py svg/812.svg data/812.json
	./json2image.py svg/843.svg data/843.json
	./json2image.py svg/845.svg data/845.json
	./json2image.py svg/855.svg data/855.json
	./json2image.py svg/856.svg data/856.json
	./json2image.py svg/857.svg data/857.json
	./json2image.py svg/N1.svg data/N1.json
	./json2image.py svg/N2.svg data/N2.json
	./json2image.py svg/N3.svg data/N3.json
	./json2image.py svg/N4.svg data/N4.json
	./json2image.py svg/N5.svg data/N5.json
	./json2image.py svg/N6.svg data/N6.json
	./json2image.py svg/N7.svg data/N7.json
	./json2image.py svg/N8.svg data/N8.json
	./json2image.py svg/N9.svg data/N9.json
	./json2image.py svg/N10.svg data/N10.json

rhine:
	./json2image.py svg/16r.svg data/16.json data/rhine.json
	./json2image.py svg/18r.svg data/18.json data/rhine.json
	./json2image.py svg/61r.svg data/61.json data/rhine.json
	./json2image.py svg/62r.svg data/62.json data/rhine.json
	./json2image.py svg/63r.svg data/63.json data/rhine.json
	./json2image.py svg/65r.svg data/65.json data/rhine.json
	./json2image.py svg/66r.svg data/66.json data/rhine.json
	./json2image.py svg/67r.svg data/67.json data/rhine.json
	./json2image.py svg/68r.svg data/68.json data/rhine.json
	./json2image.py svg/SB55r.svg data/SB55.json data/rhine.json
	./json2image.py svg/SB60r.svg data/SB60.json data/rhine.json
	./json2image.py svg/SB69r.svg data/SB69.json data/rhine.json
	./json2image.py svg/516r.svg data/516.json data/rhine.json
	./json2image.py svg/529r.svg data/529.json data/rhine.json
	./json2image.py svg/537r.svg data/537.json data/rhine.json
	./json2image.py svg/541r.svg data/541.json data/rhine.json
	./json2image.py svg/550r.svg data/550.json data/rhine.json
	./json2image.py svg/551r.svg data/551.json data/rhine.json
	./json2image.py svg/600r.svg data/600.json data/rhine.json
	./json2image.py svg/601r.svg data/601.json data/rhine.json
	./json2image.py svg/602r.svg data/602.json data/rhine.json
	./json2image.py svg/603r.svg data/603.json data/rhine.json
	./json2image.py svg/604r.svg data/604.json data/rhine.json
	./json2image.py svg/605r.svg data/605.json data/rhine.json
	./json2image.py svg/606r.svg data/606.json data/rhine.json
	./json2image.py svg/607r.svg data/607.json data/rhine.json
	./json2image.py svg/608r.svg data/608.json data/rhine.json
	./json2image.py svg/609r.svg data/609.json data/rhine.json
	./json2image.py svg/610r.svg data/610.json data/rhine.json
	./json2image.py svg/611r.svg data/611.json data/rhine.json
	./json2image.py svg/612r.svg data/612.json data/rhine.json
	./json2image.py svg/613r.svg data/613.json data/rhine.json
	./json2image.py svg/614r.svg data/614.json data/rhine.json
	./json2image.py svg/615r.svg data/615.json data/rhine.json
	./json2image.py svg/630r.svg data/630.json data/rhine.json
	./json2image.py svg/631r.svg data/631.json data/rhine.json
	./json2image.py svg/632r.svg data/632.json data/rhine.json
	./json2image.py svg/633r.svg data/633.json data/rhine.json
	./json2image.py svg/635r.svg data/635.json data/rhine.json
	./json2image.py svg/636r.svg data/636.json data/rhine.json
	./json2image.py svg/637r.svg data/637.json data/rhine.json
	./json2image.py svg/638r.svg data/638.json data/rhine.json
	./json2image.py svg/640r.svg data/640.json data/rhine.json
	./json2image.py svg/680r.svg data/680.json data/rhine.json
	./json2image.py svg/800r.svg data/800.json data/rhine.json
	./json2image.py svg/812r.svg data/812.json data/rhine.json
	./json2image.py svg/843r.svg data/843.json data/rhine.json
	./json2image.py svg/845r.svg data/845.json data/rhine.json
	./json2image.py svg/855r.svg data/855.json data/rhine.json
	./json2image.py svg/856r.svg data/856.json data/rhine.json
	./json2image.py svg/857r.svg data/857.json data/rhine.json
	./json2image.py svg/N1r.svg data/N1.json data/rhine.json
	./json2image.py svg/N2r.svg data/N2.json data/rhine.json
	./json2image.py svg/N3r.svg data/N3.json data/rhine.json
	./json2image.py svg/N4r.svg data/N4.json data/rhine.json
	./json2image.py svg/N5r.svg data/N5.json data/rhine.json
	./json2image.py svg/N6r.svg data/N6.json data/rhine.json
	./json2image.py svg/N7r.svg data/N7.json data/rhine.json
	./json2image.py svg/N8r.svg data/N8.json data/rhine.json
	./json2image.py svg/N9r.svg data/N9.json data/rhine.json
	./json2image.py svg/N10r.svg data/N10.json data/rhine.json
	
boon:
	./json2image.py svg/16rb.svg data/16.json data/rhine.json data/boon.json
	./json2image.py svg/18rb.svg data/18.json data/rhine.json data/boon.json
	./json2image.py svg/61rb.svg data/61.json data/rhine.json data/boon.json
	./json2image.py svg/62rb.svg data/62.json data/rhine.json data/boon.json
	./json2image.py svg/63rb.svg data/63.json data/rhine.json data/boon.json
	./json2image.py svg/65rb.svg data/65.json data/rhine.json data/boon.json
	./json2image.py svg/66rb.svg data/66.json data/rhine.json data/boon.json
	./json2image.py svg/67rb.svg data/67.json data/rhine.json data/boon.json
	./json2image.py svg/68rb.svg data/68.json data/rhine.json data/boon.json
	./json2image.py svg/SB55rb.svg data/SB55.json data/rhine.json data/boon.json
	./json2image.py svg/SB60rb.svg data/SB60.json data/rhine.json data/boon.json
	./json2image.py svg/SB69rb.svg data/SB69.json data/rhine.json data/boon.json
	./json2image.py svg/516rb.svg data/516.json data/rhine.json data/boon.json
	./json2image.py svg/529rb.svg data/529.json data/rhine.json data/boon.json
	./json2image.py svg/537rb.svg data/537.json data/rhine.json data/boon.json
	./json2image.py svg/541rb.svg data/541.json data/rhine.json data/boon.json
	./json2image.py svg/550rb.svg data/550.json data/rhine.json data/boon.json
	./json2image.py svg/551rb.svg data/551.json data/rhine.json data/boon.json
	./json2image.py svg/600rb.svg data/600.json data/rhine.json data/boon.json
	./json2image.py svg/601rb.svg data/601.json data/rhine.json data/boon.json
	./json2image.py svg/602rb.svg data/602.json data/rhine.json data/boon.json
	./json2image.py svg/603rb.svg data/603.json data/rhine.json data/boon.json
	./json2image.py svg/604rb.svg data/604.json data/rhine.json data/boon.json
	./json2image.py svg/605rb.svg data/605.json data/rhine.json data/boon.json
	./json2image.py svg/606rb.svg data/606.json data/rhine.json data/boon.json
	./json2image.py svg/607rb.svg data/607.json data/rhine.json data/boon.json
	./json2image.py svg/608rb.svg data/608.json data/rhine.json data/boon.json
	./json2image.py svg/609rb.svg data/609.json data/rhine.json data/boon.json
	./json2image.py svg/610rb.svg data/610.json data/rhine.json data/boon.json
	./json2image.py svg/611rb.svg data/611.json data/rhine.json data/boon.json
	./json2image.py svg/612rb.svg data/612.json data/rhine.json data/boon.json
	./json2image.py svg/613rb.svg data/613.json data/rhine.json data/boon.json
	./json2image.py svg/614rb.svg data/614.json data/rhine.json data/boon.json
	./json2image.py svg/615rb.svg data/615.json data/rhine.json data/boon.json
	./json2image.py svg/630rb.svg data/630.json data/rhine.json data/boon.json
	./json2image.py svg/631rb.svg data/631.json data/rhine.json data/boon.json
	./json2image.py svg/632rb.svg data/632.json data/rhine.json data/boon.json
	./json2image.py svg/633rb.svg data/633.json data/rhine.json data/boon.json
	./json2image.py svg/635rb.svg data/635.json data/rhine.json data/boon.json
	./json2image.py svg/636rb.svg data/636.json data/rhine.json data/boon.json
	./json2image.py svg/637rb.svg data/637.json data/rhine.json data/boon.json
	./json2image.py svg/638rb.svg data/638.json data/rhine.json data/boon.json
	./json2image.py svg/640rb.svg data/640.json data/rhine.json data/boon.json
	./json2image.py svg/680rb.svg data/680.json data/rhine.json data/boon.json
	./json2image.py svg/800rb.svg data/800.json data/rhine.json data/boon.json
	./json2image.py svg/812rb.svg data/812.json data/rhine.json data/boon.json
	./json2image.py svg/843rb.svg data/843.json data/rhine.json data/boon.json
	./json2image.py svg/845rb.svg data/845.json data/rhine.json data/boon.json
	./json2image.py svg/855rb.svg data/855.json data/rhine.json data/boon.json
	./json2image.py svg/856rb.svg data/856.json data/rhine.json data/boon.json
	./json2image.py svg/857rb.svg data/857.json data/rhine.json data/boon.json
	./json2image.py svg/N1rb.svg data/N1.json data/rhine.json data/boon.json
	./json2image.py svg/N2rb.svg data/N2.json data/rhine.json data/boon.json
	./json2image.py svg/N3rb.svg data/N3.json data/rhine.json data/boon.json
	./json2image.py svg/N4rb.svg data/N4.json data/rhine.json data/boon.json
	./json2image.py svg/N5rb.svg data/N5.json data/rhine.json data/boon.json
	./json2image.py svg/N6rb.svg data/N6.json data/rhine.json data/boon.json
	./json2image.py svg/N7rb.svg data/N7.json data/rhine.json data/boon.json
	./json2image.py svg/N8rb.svg data/N8.json data/rhine.json data/boon.json
	./json2image.py svg/N9rb.svg data/N9.json data/rhine.json data/boon.json
	./json2image.py svg/N10rb.svg data/N10.json data/rhine.json data/boon.json
z